title: Conference Deadlines # (Maintained by @imtypist)
# email: 
description: Countdowns to targeted conference deadlines
author: 

domain: "isabelleliu630.github.io"
baseurl: ""

github_username: isabelleliu630
github_repo: conf-deadlines

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']